cabal-version:      3.0
name:               marginlab

version:            0.1.0.0

license:            BSD-3-Clause

license-file:       LICENSE

author:             Samuel Niyonkuru

maintainer:         samniyonkuru@gmail.com

category:           finance
build-type:         Simple

extra-doc-files:    CHANGELOG.md


common warnings
    ghc-options: -Wall

library
    import:           warnings

    exposed-modules: 
      Units.Types
      Units.Types.Internal
      Units.Conversions.Area
      Units.Conversions.Mass

    build-depends:    base ^>=4.20.2.0

    hs-source-dirs:   src

    default-language: GHC2024

executable marginlab
    import:           warnings

    main-is:          Main.hs

    build-depends:
        base ^>=4.20.2.0,
        marginlab

    hs-source-dirs:   app

    default-language: GHC2024

test-suite marginlab-test
    import:           warnings

    default-language: GHC2024

    type:             exitcode-stdio-1.0

    hs-source-dirs:   test

    main-is:          Main.hs

    other-modules:
      Units.TypesSpec
      Units.Conversions.AreaSpec
      Units.Conversions.MassSpec

    build-depends:
        base ^>=4.20.2.0,
        hspec,
        marginlab
